# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
dist: xenial

language: python
# Existing Python versions
matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=mypy

    - python: 2.7
      env: TOXENV=py27

    - python: 3.5
      env: TOXENV=py35
      
    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      env: TOXENV=py37

    - python: pypy
      env: TOXENV=pypy2

    - python: pypy3
      env: TOXENV=pypy3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox -r requirements.txt

# command to run tests, e.g. python setup.py test
script: tox -e $TOXENV

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: RexGalilae
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: RexGalilae/vasp_tools
    condition: $TOXENV == p37
